language: node_js

node_js:
  - '10'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - docker

env:
  global:
    - CXX=g++-4.8

before_install:
  - cd server && npm install && cd ..

script:
  - cd server && npm test && cd ..
