language: node_js

node_js:
  - '10'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - docker

env:
  global:
    - CXX=g++-4.8

before_install:
  - cd server && npm install && cd ..
  - npm install codecov typescript -g

script:
  - cd server && npm run eslint && cd ..
  - cd server && npm run checkjs && cd ..
  - cd server && npm run coverage && codecov && cd ..
