version: 2.1
jobs:
  test-server:
    working_directory: ~/gladys-test/server # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:10
    steps: # a collection of executable commands
      - checkout:
          path: ~/gladys-test
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get install -y libudev-dev sqlite3 openssl
            wget https://github.com/OpenZWave/open-zwave/archive/V1.5.zip
            unzip V1.5.zip
            cd open-zwave-1.5
            sudo make install
            sudo ldconfig /usr/local/lib /usr/local/lib64
      - run:
          name: Install global dependencies
          command: 'sudo npm install typescript node-gyp npm@latest -g'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run prettier
          command: npm run prettier-check
      - run:
          name: Run eslint
          command: npm run eslint
      - run:
          name: Tests with coverage
          command: npm run coverage
      - run:
          name: Display coverage file for debug
          command: cat coverage.lcov
      - run:
          name: Save coverage
          command: npm run push-coverage
  test-front:
    working_directory: ~/gladys-test/front # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:10
    steps: # a collection of executable commands
      - checkout:
          path: ~/gladys-test
      - run:
          name: Install global dependencies
          command: 'sudo npm install codecov npm@latest -g'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run prettier
          command: npm run prettier-check
      - run:
          name: Run eslint
          command: npm run eslint
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-server
      - test-front
